name: a workflow for London Transit project
on: 
  push:
    branches:
      - main
      # For testing only, remove when done
      - 'github-actions'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          REACT_APP_MAPBOX_API: ${{ secrets.MAPBOX_API }}
          GENERATE_SOURCEMAP: false
      - name: Build the app
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build